/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// ReportTransitioning reports the extension status as "transitioning"

extern GoInterface ReportTransitioning(GoString p0, GoString p1);

// ReportError reports the extension status as "error"

extern GoInterface ReportError(GoString p0, GoString p1);

// ReportSuccess reports the extension status as "success"

extern GoInterface ReportSuccess(GoString p0, GoString p1);

// UpdateSeqNum updates the sequence number to the most recent sequence number as long as it hasn't been processed

extern GoInterface UpdateSeqNum();

/* Return type for GetPublicSettings */
struct GetPublicSettings_return {
	GoString r0;
	GoSlice r1;
};

extern struct GetPublicSettings_return GetPublicSettings();

/* Return type for GetProtectedSettings */
struct GetProtectedSettings_return {
	GoString r0;
	GoString r1;
	GoSlice r2;
	GoString r3;
	GoString r4;
};

extern struct GetProtectedSettings_return GetProtectedSettings();

#ifdef __cplusplus
}
#endif
